export {
  CredentialStore,
  SyncCredentialStore,
  CredentialBackend,
  CredentialStoreOptions,
  CredentialError,
  DpapiFailureInfo,
  WindowsDpapiCredentialStore,
  PlaintextCredentialStore,
  BackendProbe,
  CandidateOsBackend,
  ProbeBackendsOptions,
  BackendCtor,
  BackendSelection,
  CreateCredentialStoreOptions,
  SECRET_REF_PREFIX,
  defaultSecretsFile,
  makeSecretRef,
  parseSecretRef,
  probeBackends,
  selectBackend,
  createCredentialStore,
} from './CredentialStore.js';